services:
    userservicedb:
        container_name: userservicedb
        environment:
            POSTGRES_DB: userservicedb
        extends:
            file: common-config.yml
            service: db-service
        ports:
            - 5432:5432

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
            PGADMIN_CONFIG_SERVER_MODE: "True"
            PGADMIN_LOG_LEVEL: "DEBUG"
        depends_on:
            userservicedb:
                condition: service_healthy
        volumes:
            - ./postgres_db_data/servers.json:/pgadmin4/servers.json
            - ./postgres_db_data/pgpass:/pgpass
        user: root
        entrypoint: /bin/sh -c "chmod 600 /pgpass && /entrypoint.sh"
        extends:
            file: common-config.yml
            service: base-service

#    userservice:
#        image: d0niiel/userservice:s1
#        container_name: userservice
#        extends:
#            file: common-config.yml
#            service: app-service
#        ports:
#            - "8080:8080"
#        depends_on:
#            userservicedb:
#                condition: service_healthy
#        environment:
#            SPRING_DATASOURCE_URL: jdbc:postgresql://userservicedb:5432/userservicedb
#            SPRING_DATASOURCE_USERNAME: postgres
#            SPRING_DATASOURCE_PASSWORD: postgres


networks:
    rentspace:
        driver: bridge
